import { SEOHead } from '@/components/SEOHead';
import { Navbar } from '@/components/Navbar';
import { Footer } from '@/components/Footer';

export default function Terms() {
  return (
    <div className="min-h-screen bg-background">
      <SEOHead
        title="Terms of Service - PDFStudy.online"
        description="Read the terms and conditions for using PDFStudy.online. Understand your rights and responsibilities when using our AI study platform."
        keywords="pdfstudy terms of service, user agreement, terms and conditions, AI study platform terms"
        canonicalUrl="https://pdfstudy.online/terms"
      />
      <Navbar />
      
      <main className="py-16 md:py-24">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto prose prose-neutral dark:prose-invert">
            <h1 className="text-4xl font-bold text-foreground mb-8">Terms of Service</h1>
            <p className="text-muted-foreground mb-8">Last updated: January 1, 2026</p>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-foreground mb-4">1. Agreement to Terms</h2>
              <p className="text-muted-foreground leading-relaxed">
                By accessing or using PDFStudy.online, you agree to be bound by these Terms of Service. 
                If you disagree with any part of these terms, you may not access the service.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-foreground mb-4">2. Description of Service</h2>
              <p className="text-muted-foreground leading-relaxed">
                PDFStudy.online is an AI-powered educational platform that provides:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2 mt-4">
                <li>Document-to-notes conversion</li>
                <li>Flashcard generation</li>
                <li>Practice test creation</li>
                <li>AI tutoring assistance</li>
                <li>Video-to-study material conversion</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-foreground mb-4">3. User Accounts</h2>
              <p className="text-muted-foreground leading-relaxed">
                When you create an account, you must provide accurate and complete information. 
                You are responsible for:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2 mt-4">
                <li>Maintaining the confidentiality of your account</li>
                <li>All activities that occur under your account</li>
                <li>Notifying us immediately of any unauthorized use</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-foreground mb-4">4. Acceptable Use</h2>
              <p className="text-muted-foreground leading-relaxed">You agree NOT to:</p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2 mt-4">
                <li>Upload copyrighted content you don't have rights to use</li>
                <li>Use the service for any illegal purpose</li>
                <li>Attempt to access other users' accounts</li>
                <li>Interfere with or disrupt the service</li>
                <li>Upload malicious code or files</li>
                <li>Use the service to generate harmful or inappropriate content</li>
                <li>Resell or redistribute AI-generated content commercially without permission</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-foreground mb-4">5. Content Ownership</h2>
              
              <h3 className="text-xl font-medium text-foreground mb-3">5.1 Your Content</h3>
              <p className="text-muted-foreground leading-relaxed mb-4">
                You retain ownership of the original content you upload. By uploading content, you grant us 
                a license to process it for providing our services.
              </p>

              <h3 className="text-xl font-medium text-foreground mb-3">5.2 AI-Generated Content</h3>
              <p className="text-muted-foreground leading-relaxed">
                Study materials generated by our AI (notes, flashcards, tests) are provided for your personal 
                educational use. You may share them with other students on our platform.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-foreground mb-4">6. Intellectual Property</h2>
              <p className="text-muted-foreground leading-relaxed">
                The service, including its original content, features, and functionality, is owned by 
                PDFStudy.online and is protected by international copyright, trademark, and other laws.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-foreground mb-4">7. AI Limitations</h2>
              <p className="text-muted-foreground leading-relaxed">
                While we strive for accuracy, AI-generated content may contain errors. You should:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2 mt-4">
                <li>Review all generated materials for accuracy</li>
                <li>Use AI content as a study aid, not as your sole source of information</li>
                <li>Consult official textbooks and instructors for critical information</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-foreground mb-4">8. Disclaimer of Warranties</h2>
              <p className="text-muted-foreground leading-relaxed">
                The service is provided "as is" without warranties of any kind, either express or implied. 
                We do not guarantee that the service will be uninterrupted, secure, or error-free.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-foreground mb-4">9. Limitation of Liability</h2>
              <p className="text-muted-foreground leading-relaxed">
                PDFStudy.online shall not be liable for any indirect, incidental, special, consequential, 
                or punitive damages resulting from your use of the service.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-foreground mb-4">10. Termination</h2>
              <p className="text-muted-foreground leading-relaxed">
                We may terminate or suspend your account immediately, without prior notice, for conduct that 
                we believe violates these Terms or is harmful to other users or the service.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-foreground mb-4">11. Changes to Terms</h2>
              <p className="text-muted-foreground leading-relaxed">
                We reserve the right to modify these terms at any time. We will notify users of significant 
                changes via email or through the service.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-foreground mb-4">12. Contact</h2>
              <p className="text-muted-foreground leading-relaxed">
                For questions about these Terms, please contact us at:
              </p>
              <p className="text-muted-foreground mt-4">
                Email: <a href="mailto:legal@pdfstudy.online" className="text-primary hover:underline">legal@pdfstudy.online</a>
              </p>
            </section>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
