interface Message {
  role: 'user' | 'assistant';
  content: string;
}

interface QAPDFData {
  messages: Message[];
  content: string;
  title?: string;
}

export const generateQAPDF = (data: QAPDFData): void => {
  const { messages, content, title = 'AI Q&A Conversation' } = data;

  // Generate HTML content
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>${title} - PDFStudy.online</title>
      <style>
        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }
        body {
          font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
          line-height: 1.6;
          color: #333;
          padding: 40px;
          max-width: 800px;
          margin: 0 auto;
        }
        .header {
          text-align: center;
          padding-bottom: 20px;
          border-bottom: 2px solid #6366f1;
          margin-bottom: 30px;
        }
        .logo {
          font-size: 28px;
          font-weight: bold;
          color: #6366f1;
          margin-bottom: 10px;
        }
        .title {
          font-size: 24px;
          color: #1f2937;
          margin-bottom: 10px;
        }
        .content-preview {
          font-size: 12px;
          color: #6b7280;
          margin-bottom: 15px;
          padding: 10px;
          background: #f9fafb;
          border-radius: 4px;
          max-height: 100px;
          overflow: hidden;
        }
        .message {
          margin-bottom: 20px;
          padding: 15px;
          border-radius: 8px;
        }
        .message-user {
          background: #e0e7ff;
          border-left: 4px solid #6366f1;
          margin-left: 40px;
        }
        .message-assistant {
          background: #f9fafb;
          border-left: 4px solid #10b981;
          margin-right: 40px;
        }
        .message-role {
          font-size: 12px;
          font-weight: 600;
          text-transform: uppercase;
          color: #6b7280;
          margin-bottom: 8px;
        }
        .message-content {
          font-size: 14px;
          color: #374151;
          line-height: 1.7;
        }
        .message-content p {
          margin-bottom: 8px;
        }
        .message-content ul, .message-content ol {
          margin-left: 20px;
          margin-bottom: 8px;
        }
        .message-content li {
          margin-bottom: 4px;
        }
        .footer {
          margin-top: 40px;
          padding-top: 20px;
          border-top: 1px solid #e5e7eb;
          text-align: center;
          color: #9ca3af;
          font-size: 12px;
        }
        @media print {
          body {
            padding: 20px;
          }
          .message {
            break-inside: avoid;
          }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="logo">📚 PDFStudy.online</div>
        <div class="title">${title}</div>
        ${content ? `
          <div class="content-preview">
            <strong>Source Content:</strong> ${content.substring(0, 200)}${content.length > 200 ? '...' : ''}
          </div>
        ` : ''}
      </div>

      <div class="conversation">
        ${messages.map((message, index) => `
          <div class="message message-${message.role}">
            <div class="message-role">${message.role === 'user' ? '👤 You' : '🤖 AI Tutor'}</div>
            <div class="message-content">${message.content.replace(/\n/g, '<br>')}</div>
          </div>
        `).join('')}
      </div>

      <div class="footer">
        Generated by PDFStudy.online • ${new Date().toLocaleDateString('en-US', { 
          day: '2-digit', 
          month: 'long', 
          year: 'numeric' 
        })}
      </div>
    </body>
    </html>
  `;

  // Create and download PDF using print
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(htmlContent);
    printWindow.document.close();
    
    // Wait for content to load then trigger print
    printWindow.onload = () => {
      setTimeout(() => {
        printWindow.print();
      }, 250);
    };
  }
};


